### ISSUE TITLE
Error 503 - Invalid tonce value

### ISSUE THREAD

**Issue by pablobb** [Rav3nPL/swapbot#1]
Witam, jak w tytule, bot przestał działać. Wygenerowanie nowych kluczy nie zmienia sytuacji. Jedyne co się zmieniło to zmiana na czas zimowy, jedyny ślad w google wskazywałby że może to mieć związek.

Pozdrawiam i dzięki za ten tool.

**Comment by Rav3nPL** [comment]
Synchronizacja zegarka na komuterze nie pomogła?
Bot odczytuje czas w UTC więc zmiana czasu nie powinna miec wpływu.

**Comment by pablobb** [comment]
Dziwna sprawa, czas miałem w systemie dobry, ale restart po msc pracy non stop, potem sync z time.window.com i bot działa ponownie. Mystery solved.
